# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish EnchantmentProgrammingLanguage.csproj -c Release -o _out /p:PublishTrimmed=true
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: GitHub Pages Blazor WASM
    # You may pin to the exact commit or the version.
    # uses: na1307/blazor-github-pages@da07d46d47ad5038f3caf9a3ba5a4a5cdad5f49b
      uses: na1307/blazor-github-pages@v3.0
      with:
        # Path of project (.csproj)
        project-path: EnchantmentProgrammingLanguage.csproj
        # Path to output in Publish step
        publish-path: _out
        # Set to true only when running this action from the default GitHub Pages repository ({ID}.github.io).
        main-repo: true
        # Whether to apply repository-specific modifications to 404.html as well. This only takes effect when main-repo is false.
        fix-404: true

    - name: Remove symlinks
      run: find _out -type l -delete
  
    - uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: _out/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
          
